"""
Report Exporter Module
Generates clinical-grade PDF and DOCX documents with prominent AI attribution notices.
"""

import io
import json
from datetime import datetime
from typing import Dict, Any, List

import docx
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement, parse_xml
from docx.oxml.ns import nsdecls, qn

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable,
    KeepTogether,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from src.models.schemas import MedicalReportData, TestItem, TestCategory


AI_EXPERT_DISCLAIMER = (
    "CLINICAL DECISION SUPPORT & EXPERT CONSULTATION MANDATE: "
    "This document contains automated clinical analysis generated by an Artificial Intelligence (AI) system. "
    "All findings, risk stratifications, and biomarker evaluations are intended strictly for diagnostic screening "
    "and assistive decision-support purposes. This report does NOT replace professional medical diagnosis or clinical pathology judgment. "
    "MANDATORY REQUIREMENT: Yeh analysis AI dwara ki gayi hai. Kisi bhi medication, treatment ya medical decision se pehle "
    "clinical confirmation ke liye yeh report kisi certified medical physician, pathologist, ya healthcare expert ko zaroor dikhaayein."
)

STATUS_LEGEND_NOTICE = (
    "STATUS ATTRIBUTION: Tests flagged with '[Mentioned in Report]' were explicitly indicated on the original laboratory document. "
    "Tests flagged with '[AI Assumption]' were derived mathematically by comparing observed patient levels against reported reference intervals."
)


def generate_pdf_report(report_data: MedicalReportData) -> bytes:
    """Generate an official, clinical-grade PDF document."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=15,
        leading=18,
        textColor=colors.HexColor('#0f172a')
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#64748b')
    )
    
    disclaimer_style = ParagraphStyle(
        'DisclaimerText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#7f1d1d')
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=8,
        spaceAfter=4
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#334155')
    )

    table_header = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7.5,
        leading=9.5,
        textColor=colors.white
    )

    table_body = ParagraphStyle(
        'TableBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=9.5,
        textColor=colors.HexColor('#0f172a')
    )

    story = []

    # Title & Subtitle
    story.append(Paragraph("CLINICAL LABORATORY DIAGNOSTIC EVALUATION REPORT", title_style))
    story.append(Paragraph("Automated Pathology Screening & Biomarker Extraction Verification System", subtitle_style))
    story.append(Spacer(1, 8))

    # Prominent Disclaimer Callout Box
    disclaimer_data = [
        [
            Paragraph(
                f"<b>CRITICAL MEDICAL NOTICE:</b> {AI_EXPERT_DISCLAIMER}<br/><br/>"
                f"<b>STATUS ATTRIBUTION:</b> {STATUS_LEGEND_NOTICE}",
                disclaimer_style
            )
        ]
    ]
    disclaimer_table = Table(disclaimer_data, colWidths=[540])
    disclaimer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fef2f2')),
        ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor('#ef4444')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(disclaimer_table)
    story.append(Spacer(1, 10))

    # Patient Demographics
    story.append(Paragraph("PATIENT DEMOGRAPHICS & INGESTION METADATA", section_heading))
    p = report_data.patient_info
    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    demo_data = [
        [
            Paragraph(f"<b>Patient Name:</b> {p.name}", body_style),
            Paragraph(f"<b>Specimen Date:</b> {p.report_date}", body_style)
        ],
        [
            Paragraph(f"<b>Age / Gender:</b> {p.age} / {p.gender}", body_style),
            Paragraph(f"<b>Accession ID:</b> {p.lab_number}", body_style)
        ],
        [
            Paragraph(f"<b>Referring Physician:</b> {p.referring_doctor}", body_style),
            Paragraph(f"<b>Generated On:</b> {timestamp_str}", body_style)
        ]
    ]
    demo_table = Table(demo_data, colWidths=[270, 270])
    demo_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(demo_table)
    story.append(Spacer(1, 10))

    # Risk Stratification Summary
    if report_data.diagnosis:
        diag = report_data.diagnosis
        story.append(Paragraph("CLINICAL RISK STRATIFICATION INDEX", section_heading))
        risk_data = [
            [
                Paragraph("<b>Overall Health Index</b>", body_style),
                Paragraph(f"<b>{diag.risk_assessment.overall_risk.upper()}</b>", body_style),
                Paragraph("<b>Cardiovascular Risk</b>", body_style),
                Paragraph(f"<b>{diag.risk_assessment.cardiovascular_risk.title()}</b>", body_style),
                Paragraph("<b>Metabolic Risk</b>", body_style),
                Paragraph(f"<b>{diag.risk_assessment.diabetes_risk.title()}</b>", body_style)
            ]
        ]
        risk_table = Table(risk_data, colWidths=[110, 70, 110, 70, 110, 70])
        risk_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f1f5f9')),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#94a3b8')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(risk_table)
        story.append(Spacer(1, 10))

    # Laboratory Biomarker Tables
    story.append(Paragraph("LABORATORY BIOMARKER PANELS", section_heading))

    for cat in report_data.test_categories:
        if not cat.tests:
            continue
        
        story.append(Paragraph(f"Panel: {cat.category}", section_heading))

        headers = ["Biomarker", "Observed", "Reference", "Status", "Attribution", "Clinical Correlate"]
        table_rows = [[Paragraph(h, table_header) for h in headers]]

        for t in cat.tests:
            val_disp = f"{t.value} {t.unit}".strip()
            is_ai = getattr(t, "is_ai_assumption", False) or getattr(t, "status_source", "") == "ai_assumption"
            status_text = t.status.title()
            source_text = "AI Assumption" if is_ai else "Report Mention"
            signif = t.clinical_significance or "Within normal bounds"

            status_color = "#dc2626" if t.status.lower() in ["high", "critical", "abnormal"] else (
                "#2563eb" if t.status.lower() == "low" else (
                    "#d97706" if t.status.lower() == "borderline" else "#16a34a"
                )
            )

            row = [
                Paragraph(f"<b>{t.test_name}</b>", table_body),
                Paragraph(val_disp, table_body),
                Paragraph(t.reference_range, table_body),
                Paragraph(f"<font color='{status_color}'><b>{status_text}</b></font>", table_body),
                Paragraph(f"<i>{source_text}</i>", table_body),
                Paragraph(signif, table_body)
            ]
            table_rows.append(row)

        panel_table = Table(table_rows, colWidths=[110, 65, 80, 55, 75, 155])
        panel_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(panel_table)
        story.append(Spacer(1, 8))

    # Clinical Narrative & Recommendations
    if report_data.diagnosis:
        diag = report_data.diagnosis

        if diag.red_flags:
            story.append(Paragraph("CRITICAL PATHOLOGY ALERTS", section_heading))
            alerts_text = "<br/>".join([f"• <b>{rf}</b>" for rf in diag.red_flags])
            alert_table = Table([[Paragraph(alerts_text, disclaimer_style)]], colWidths=[540])
            alert_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fef2f2')),
                ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#dc2626')),
                ('PADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(alert_table)
            story.append(Spacer(1, 8))

        if diag.summary:
            story.append(Paragraph("CLINICAL EXECUTIVE SUMMARY", section_heading))
            story.append(Paragraph(diag.summary, body_style))
            story.append(Spacer(1, 8))

        if diag.recommendations:
            story.append(Paragraph("EVIDENCE-BASED RECOMMENDATIONS", section_heading))
            for rec in diag.recommendations:
                rec_text = f"• <b>[{rec.priority.upper()}] {rec.category.title()}:</b> {rec.recommendation}"
                if rec.rationale:
                    rec_text += f" <i>(Rationale: {rec.rationale})</i>"
                story.append(Paragraph(rec_text, body_style))
            story.append(Spacer(1, 8))

    # Final Expert Sign-Off Notice
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1')))
    story.append(Spacer(1, 5))
    story.append(Paragraph(
        "<b>CLINICAL VALIDATION REQUIREMENT:</b> This automated diagnostic summary requires formal correlation by an attending physician. "
        "Do not alter dosage or initiate medication without clinical supervision.",
        disclaimer_style
    ))

    doc.build(story)
    return buffer.getvalue()


def generate_docx_report(report_data: MedicalReportData) -> bytes:
    """Generate an official Microsoft Word (.docx) clinical report document."""
    doc = docx.Document()

    # Set 0.5 inch margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(0.5)
        section.bottom_margin = Inches(0.5)
        section.left_margin = Inches(0.5)
        section.right_margin = Inches(0.5)

    # Document Title
    title = doc.add_heading("CLINICAL LABORATORY DIAGNOSTIC EVALUATION REPORT", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    for run in title.runs:
        run.font.name = "Arial"
        run.font.size = Pt(16)
        run.font.bold = True
        run.font.color.rgb = RGBColor(15, 23, 42)

    sub = doc.add_paragraph("Automated Pathology Screening & Biomarker Extraction Verification System")
    for run in sub.runs:
        run.font.name = "Arial"
        run.font.size = Pt(9.5)
        run.font.color.rgb = RGBColor(100, 116, 139)

    # Prominent AI & Expert Consultation Notice Callout Box
    notice_table = doc.add_table(rows=1, cols=1)
    notice_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    notice_cell = notice_table.cell(0, 0)
    
    # Red background styling for callout
    shading_elm = parse_xml(r'<w:shd {} w:fill="FEF2F2"/>'.format(nsdecls('w')))
    notice_cell._tc.get_or_add_tcPr().append(shading_elm)

    p_disc = notice_cell.paragraphs[0]
    r_title = p_disc.add_run("CRITICAL MEDICAL NOTICE:\n")
    r_title.bold = True
    r_title.font.color.rgb = RGBColor(185, 28, 28)
    r_title.font.size = Pt(9)

    r_body = p_disc.add_run(AI_EXPERT_DISCLAIMER + "\n\n")
    r_body.font.color.rgb = RGBColor(185, 28, 28)
    r_body.font.size = Pt(8.5)

    r_leg = p_disc.add_run(STATUS_LEGEND_NOTICE)
    r_leg.font.color.rgb = RGBColor(100, 116, 139)
    r_leg.font.size = Pt(8)

    doc.add_paragraph()  # Spacing

    # Patient Demographics
    doc.add_heading("PATIENT DEMOGRAPHICS & INGESTION METADATA", level=2)
    p = report_data.patient_info
    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    demo_table = doc.add_table(rows=3, cols=2)
    demo_table.alignment = WD_TABLE_ALIGNMENT.CENTER
    
    demo_items = [
        (f"Patient Name: {p.name}", f"Specimen Date: {p.report_date}"),
        (f"Age / Gender: {p.age} / {p.gender}", f"Accession / Lab ID: {p.lab_number}"),
        (f"Referring Physician: {p.referring_doctor}", f"Generated On: {timestamp_str}")
    ]

    for row_idx, (col1_txt, col2_txt) in enumerate(demo_items):
        cell1 = demo_table.cell(row_idx, 0)
        cell2 = demo_table.cell(row_idx, 1)
        cell1.text = col1_txt
        cell2.text = col2_txt
        for cell in (cell1, cell2):
            cell.paragraphs[0].runs[0].font.size = Pt(9)

    doc.add_paragraph()

    # Risk Assessment
    if report_data.diagnosis:
        diag = report_data.diagnosis
        doc.add_heading("CLINICAL RISK STRATIFICATION INDEX", level=2)
        r_para = doc.add_paragraph()
        r_para.add_run(f"• Overall Health Risk: ").bold = True
        r_para.add_run(f"{diag.risk_assessment.overall_risk.upper()}\n")
        r_para.add_run(f"• Cardiovascular Risk: ").bold = True
        r_para.add_run(f"{diag.risk_assessment.cardiovascular_risk.title()}\n")
        r_para.add_run(f"• Metabolic / Glycemic Risk: ").bold = True
        r_para.add_run(f"{diag.risk_assessment.diabetes_risk.title()}")

    # Laboratory Biomarkers
    doc.add_heading("LABORATORY BIOMARKER PANELS", level=2)

    for cat in report_data.test_categories:
        if not cat.tests:
            continue

        doc.add_heading(f"Panel: {cat.category}", level=3)
        t_table = doc.add_table(rows=1 + len(cat.tests), cols=6)
        t_table.alignment = WD_TABLE_ALIGNMENT.CENTER

        headers = ["Biomarker", "Observed", "Reference", "Status", "Attribution", "Clinical Correlate"]
        for c_idx, h_name in enumerate(headers):
            cell = t_table.cell(0, c_idx)
            cell.text = h_name
            shd = parse_xml(r'<w:shd {} w:fill="0F172A"/>'.format(nsdecls('w')))
            cell._tc.get_or_add_tcPr().append(shd)
            for r in cell.paragraphs[0].runs:
                r.font.color.rgb = RGBColor(255, 255, 255)
                r.font.bold = True
                r.font.size = Pt(8.5)

        for r_idx, t in enumerate(cat.tests, start=1):
            val_disp = f"{t.value} {t.unit}".strip()
            is_ai = getattr(t, "is_ai_assumption", False) or getattr(t, "status_source", "") == "ai_assumption"
            status_text = t.status.title()
            source_text = "AI Assumption" if is_ai else "Report Mention"
            signif = t.clinical_significance or "Within normal bounds"

            row_data = [t.test_name, val_disp, t.reference_range, status_text, source_text, signif]
            for c_idx, val in enumerate(row_data):
                cell = t_table.cell(r_idx, c_idx)
                cell.text = str(val)
                p_run = cell.paragraphs[0].runs[0]
                p_run.font.size = Pt(8)

                if c_idx == 3:  # Status column color
                    p_run.bold = True
                    if t.status.lower() in ["high", "critical", "abnormal"]:
                        p_run.font.color.rgb = RGBColor(220, 38, 38)
                    elif t.status.lower() == "low":
                        p_run.font.color.rgb = RGBColor(37, 99, 235)
                    elif t.status.lower() == "borderline":
                        p_run.font.color.rgb = RGBColor(217, 119, 6)
                    else:
                        p_run.font.color.rgb = RGBColor(22, 163, 74)

        doc.add_paragraph()

    # Recommendations & Critical Observations
    if report_data.diagnosis:
        diag = report_data.diagnosis
        if diag.red_flags:
            doc.add_heading("CRITICAL ALERTS REQUIRING ATTENTION", level=2)
            for rf in diag.red_flags:
                p_rf = doc.add_paragraph(f"• {rf}")
                p_rf.runs[0].font.bold = True
                p_rf.runs[0].font.color.rgb = RGBColor(220, 38, 38)

        if diag.summary:
            doc.add_heading("CLINICAL NARRATIVE SUMMARY", level=2)
            doc.add_paragraph(diag.summary)

        if diag.recommendations:
            doc.add_heading("EVIDENCE-BASED CLINICAL RECOMMENDATIONS", level=2)
            for rec in diag.recommendations:
                p_rec = doc.add_paragraph(f"• [{rec.priority.upper()}] {rec.category.title()}: {rec.recommendation}")
                if rec.rationale:
                    p_rec.add_run(f" (Rationale: {rec.rationale})").italic = True

    # Final Disclaimer Footer
    doc.add_paragraph()
    footer_p = doc.add_paragraph("MANDATORY CLINICAL VALIDATION: This report contains automated AI screening conclusions. Consult a certified medical practitioner or pathologist before taking clinical action.")
    footer_p.runs[0].font.size = Pt(8)
    footer_p.runs[0].font.color.rgb = RGBColor(148, 163, 184)
    footer_p.runs[0].italic = True

    docx_buffer = io.BytesIO()
    doc.save(docx_buffer)
    return docx_buffer.getvalue()


def generate_structured_json(report_data: MedicalReportData) -> str:
    """Export enriched structured health data with explicit AI disclaimer metadata."""
    dump = report_data.model_dump()
    dump["ai_analysis_metadata"] = {
        "is_ai_analysis": True,
        "screening_notice": "AI-generated automated laboratory screening and decision support.",
        "expert_confirmation_mandatory": True,
        "advisory": (
            "Yeh analysis AI dwara generate ki gayi hai. Kisi bhi biological diagnosis, medication, "
            "ya treatment shuru karne se pehle confirmation ke liye report ko kisi qualified doctor, "
            "pathologist, ya medical expert ko zaroor dikhaayein."
        ),
        "disclaimer_statement": AI_EXPERT_DISCLAIMER,
        "status_attribution_legend": STATUS_LEGEND_NOTICE,
        "generated_timestamp": datetime.now().isoformat()
    }
    return json.dumps(dump, indent=2, default=str)
